#!/usr/bin/env bash

set -e

FRONTEND_VERSION="20230406083236"

python3 -m pip install -U --target=./custom_components/react "react_frontend==$FRONTEND_VERSION"
rm -rf ./custom_components/react/*.dist-info